export const GET_TRIPS_REQUEST = "GET_TRIPS_REQUEST";
export const GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS";
export const GET_TRIPS_FAIL = "GET_TRIPS_FAIL";

export const GET_TRIP_DETAILS_REQUEST = "GET_TRIP_DETAILS_REQUEST";
export const GET_TRIP_DETAILS_SUCCESS = "GET_TRIP_DETAILS_SUCCESS";
export const GET_TRIP_DETAILS_FAIL = "GET_TRIP_DETAILS_FAIL";
export const GET_TRIP_DETAILS_RESET = "GET_TRIP_DETAILS_RESET";
